WebApp/Controllers/TestsController.cs
using System.Data.Entity;
using System.Threading.Tasks;
using System.Net;
using System.Linq;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using WebApp.Models;

namespace WebApp.Controllers {

    public class TestsController : Controller {
        private WebAppDbContext db = new WebAppDbContext();

        // GET: Tests
        public async Task<ActionResult> Index() {
            return View(await db.Tests.ToListAsync());
        }

        // GET: Tests/Details/5
        public async Task<ActionResult> Details(int? id) {
            if(id == null) {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Test test = await db.Tests.FindAsync(id);
            if(test == null) {
                return HttpNotFound();
            }
            return View(test);
        }

        // GET: Tests/Edit/5
        public async Task<ActionResult> Edit(int? id) {
            if(id == null) {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Test test = await db.Tests.FindAsync(id);
            if(test == null) {
                return HttpNotFound();
            }
            return View(test);
        }

        // POST: Tests/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "TestId,Title")] Test test) {
            if(ModelState.IsValid) {
                db.Entry(test).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(test);
        }

        // GET: Tests/Scores/5
        public async Task<ActionResult> Scores() {
            return View(await db.TestScores.ToListAsync());
        }

        protected override void Dispose(bool disposing) {
            if(disposing) {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }

    public class TakeTestController : Controller {

        WebAppDbContext db = new WebAppDbContext();

        // GET: TakeTest
        [Authorize(Roles="Student")]
        public ActionResult Index() {

            var userId = User.Identity.GetUserId();
            ViewBag.userId = db.Students.Where(s => s.UserId == userId).First().StudentId;

            return View();
        }
    }
}

WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - XYZ School Network</title>
    @RenderSection("_base", required: false)
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <header>
        <nav class="top-nav">
            <div class="container">
                <strong class="brand">XYZ School Network</strong>
                @Html.Partial("_LoginPartial")
            </div>
        </nav>
    </header>
    <div class="container">
        @RenderBody()

    </div>
    @Html.Partial("_messenger")
    @Scripts.Render("~/bundles/jquery")
    <script type="text/javascript" src="~/Scripts/jquery.signalR-2.1.2.min.js"></script>
    <script src="@Url.Content("~/signalr/hubs")"></script>
    <script type="text/javascript" src="~/Scripts/script.js"></script>
    @RenderSection("scripts", required: false)
</body>
</html>

WebApp/Views/Shared/_Messenger.cshtml
@using Microsoft.AspNet.Identity
@using WebApp.Models
@{
    WebAppDbContext db = new WebAppDbContext();
    var userId = User.Identity.GetUserId();
    var user = db.Users.Where(u => u.Id == userId).First();
}
<input type="hidden" id="username" value="@user.Name">

<div id="messenger">
    <div class="head">
        <strong>Messenger</strong>
    </div>
    <div class="body">
        <div class="message-area">
            <div class="message-item">
                <div class="image">
                    <img src="/Content/Images/profile-img.png" alt="Avatar">
                </div>
                <div class="message">
                    <strong>Administrator:</strong>
                    Hello user! use the messenger to communicate with your friends and collegues in real time.
                </div>
            </div>
        </div>
        <div class="send-form">
            <div class="form">
                <input type="text" id="message" placeholder="Say something...">
                <input type="submit" id="send" value="Send">
            </div>
        </div>
    </div>
</div>

WebApp/Views/Shared/_NavPartial.cshtml
@using Microsoft.AspNet.Identity
@using WebApp.Models
<aside id="aside" class="col-sm-3">
    <div class="avatar-lockup">
@{
    WebAppDbContext db = new WebAppDbContext();
    var userId = User.Identity.GetUserId();
    var user = db.Users.Where(u => u.Id == userId).First();
    if(user.Photo != null) {
        <img src="data:img;base64,@System.Convert.ToBase64String(user.Photo)" alt="Profile Photo" />
    } else {
        <a href="@Url.Action("UploadPhoto", "Manage")" class="upload-photo">
            <span>Upload</span><img src="~/Content/Images/profile-img.png" alt="Profile Photo">
        </a>
    }
}
        <strong>@user.Name</strong>
    </div>
    <hr>
    <nav class="side-nav">
        <ul>
            @if(User.IsInRole("Admin")) {
                <li><a href="@Url.Action("Admin", "Home")"><i class="fa fa-desktop"></i>Dashboard</a></li>
                <li><a href="@Url.Action("Index", "Student")"><i class="fa fa-users"></i>Students</a></li>
                <li><a href="@Url.Action("Index", "Tests")"><i class="fa fa-book"></i>Tests</a></li>
                <li><a href="@Url.Action("Index", "Manage")"><i class="fa fa-gear"></i>Account</a></li>
            } else if(User.IsInRole("Student")) {
                <li><a href="@Url.Action("Student", "Home")"><i class="fa fa-desktop"></i>Dashboard</a></li>
                <li><a href="@Url.Action("Index", "TakeTest")"><i class="fa fa-book"></i>Tests</a></li>
                <li><a href="@Url.Action("Index", "Manage")"><i class="fa fa-gear"></i>Account</a></li>
            }
        </ul>

    </nav>

    <small class="copy">&copy; XYZ School Net. @DateTime.Now.Year</small>
</aside>